USE Lanzamientos;

TRUNCATE TABLE MODERNO_SOD;

BULK INSERT MODERNO_SOD
FROM 'C:\Proyectos\Peru\Moderno\ModernoSOD.csv'
WITH(FIELDTERMINATOR=';', FIRSTROW=2, CODEPAGE='ACP');

UPDATE A SET SubCadena =TRIM(SubCadena) FROM MODERNO_SOD A;
UPDATE A SET CODTIENDA =TRIM(CODTIENDA) FROM MODERNO_SOD A;
UPDATE A SET PuntoVenta =TRIM(PuntoVenta) FROM MODERNO_SOD A;
UPDATE A SET CategoriaLucky =TRIM(CategoriaLucky) FROM MODERNO_SOD A;
UPDATE A SET MarcaLucky =TRIM(MarcaLucky) FROM MODERNO_SOD A;
UPDATE A SET EmpresaLucky =TRIM(EmpresaLucky) FROM MODERNO_SOD A;


TRUNCATE TABLE MODERNO_SOE;

BULK INSERT MODERNO_SOE
FROM 'C:\Proyectos\Peru\Moderno\ModernoSOE.csv'
WITH(FIELDTERMINATOR=';', FIRSTROW=2, CODEPAGE='ACP');

UPDATE A SET SubCadena =TRIM(SubCadena) FROM MODERNO_SOE A;
UPDATE A SET COD_PDV =TRIM(COD_PDV) FROM MODERNO_SOE A;
UPDATE A SET TIENDA =TRIM(TIENDA) FROM MODERNO_SOE A;
UPDATE A SET CategoriaLucky =TRIM(CategoriaLucky) FROM MODERNO_SOE A;
UPDATE A SET EMPRESA =TRIM(EMPRESA) FROM MODERNO_SOE A;
UPDATE A SET MARCA =TRIM(MARCA) FROM MODERNO_SOE A;
UPDATE A SET ELEMENTO =TRIM(ELEMENTO) FROM MODERNO_SOE A;
UPDATE A SET REPORTE =TRIM(REPORTE) FROM MODERNO_SOE A;


IF OBJECT_ID(N'tempdb..#MODERNO_SOD') IS NOT NULL DROP TABLE #MODERNO_SOD;

SELECT A.Fecha, 'PONER ACA LOS NOMBRES DE LAS CADENAS CORRESPONDIENTES'Cadena, A.SubCadena, A.CODTIENDA, A.PuntoVenta, C.CAT_AFO Categoria
	   , CASE WHEN B.Marca IS NOT NULL THEN 'MARCA PROPIA' ELSE EmpresaLucky END Empresa, A.CM ShareDisplay
INTO #MODERNO_SOD 
FROM MODERNO_SOD A
	LEFT JOIN Maestro_marca_Propia B ON A.MarcaLucky = B.Marca AND A.SubCadena = B.SubCadena
	LEFT JOIN MAESTRO_SOD C ON A.CategoriaLucky = C.CAT_SOD


UPDATE #MODERNO_SOD SET SubCadena = 'SUPERMERCADOS PERUANOS'
WHERE SubCadena = 'PLAZA VEA'
--VER SI VAN A VER MS COMO VIVANDA ETC
UPDATE A SET Cadena = B.Cadena
 FROM #MODERNO_SOD A
LEFT JOIN (SELECT DISTINCT Cadena, ClienteHomologado
           FROM MAESTRO_CLIENTE) B ON A.SubCadena = B.ClienteHomologado;

	

IF OBJECT_ID('SHARE_DISPLAY') IS NOT NULL DROP TABLE SHARE_DISPLAY;

SELECT *
INTO SHARE_DISPLAY
FROM #MODERNO_SOD


IF OBJECT_ID(N'tempdb..#MODERNO_SOE') IS NOT NULL DROP TABLE #MODERNO_SOE;

SELECT A.Fecha, 'PONER ACA LOS NOMBRES DE LAS CADENAS CORRESPONDIENTES'Cadena, A.SubCadena, A.COD_PDV, A.TIENDA, B.CAT_AFO Categoria
	   , A.EMPRESA, A.MARCA, A.Cantidad, A.REPORTE
INTO #MODERNO_SOE
--select *
FROM MODERNO_SOE A
	LEFT JOIN MAESTRO_SOD B ON A.CategoriaLucky = B.CAT_SOD
	--where B.CAT_SOD is null; se necesita daar mantenimiento por ejemplo pprod peinas cual es maquila etc

Delete from #MODERNO_SOE where Categoria is null
--ojo con este delete ver hasta cuando se usa

UPDATE #MODERNO_SOE SET SubCadena = 'SUPERMERCADOS PERUANOS'
WHERE SubCadena = 'PLAZA VEA'
--VER SI VAN A VER MS COMO VIVANDA ETC
UPDATE A SET Cadena = B.Cadena
 FROM #MODERNO_SOE A
LEFT JOIN (SELECT DISTINCT Cadena, ClienteHomologado
           FROM MAESTRO_CLIENTE) B ON A.SubCadena = B.ClienteHomologado;

IF OBJECT_ID('SHARE_EXHIBITION') IS NOT NULL DROP TABLE SHARE_EXHIBITION;


SELECT *
INTO SHARE_EXHIBITION
FROM #MODERNO_SOE

----------------------------------------
--ver como subir el sov

UPDATE A SET Cadena = B.Cadena
FROM SOV A
	LEFT SELECT DISTINCT Cadena
           FROM MAESTRO_CLIENTE

IF OBJECT_ID(N'tempdb..#SOV') IS NOT NULL DROP TABLE #SOV;

SELECT *
INTO #SOV
FROM SOV;

UPDATE A SET Cadena = LOWER(Cadena) FROM #SOV A WHERE Cadena <> 'SPSA'
UPDATE A SET Cadena = REPLACE(Cadena,'tottus','Tottus') FROM #SOV A WHERE Cadena = 'tottus'
UPDATE A SET Cadena = REPLACE(Cadena,'cencosud','Cencosud') FROM #SOV A WHERE Cadena = 'cencosud'

IF OBJECT_ID('SHARE_VALUE') IS NOT NULL DROP TABLE SHARE_VALUE;

SELECT *
INTO SHARE_VALUE
FROM #SOV

---------------------------------------------------
-- ver como cargar presencialidad
